### ISSUE TITLE
Ubuntu - Using Package Manager Method - VM freezes after reboot

### ISSUE THREAD

**Issue by anmolsagarwal** [CamFlow/website#10]
Hello,
I am using a Ubuntu 18.04.2 VM on VirtualBox. I tried installing CamFlow using the Package manager instructions.

I thought I had installed CamFlow successfully, but when I reboot the machine after installing CamFlow the machine does not boot up. It is still loading a few hours later.

Do you know what could be causing this issue? What are the resource requirements for CamFlow to work on a virtual machine.

**Comment by tfjmp** [comment]
Does the issue occur if building from source?

**Comment by anmolsagarwal** [comment]
I have not been able to build from source on my machine. So far, it has taken three days and it is not finished. How long does it take to build from source?

**Comment by tfjmp** [comment]
It should be much, much faster than this (obviously it would depend on your hardware). It takes at most an hour on my machine.

This vagrant script should set you up a working ubuntu environment (just tested it): https://github.com/CamFlow/vagrant/tree/master/deb

**Comment by anmolsagarwal** [comment]
I was able to get it installed on a Linux host. A Linux VM does not work.
Thank you for all of your help.
