### ISSUE TITLE
Link broken or incomplete.

### ISSUE THREAD

**Issue by xyzwwwww** [CamFlow/website#9]
You can check here to see what this data means. Publishing the provenance is the job of camflowd, let’s look at its configuration to understand what it is doing:

http://camflow.org/w3c.md

**Comment by michael-hahn** [comment]
Are you sure you are looking at the correct page? If you want to know about `camflowd`, try this link: http://camflow.org/#recording

The link you provided seems to be incorrect. Try this and you will see:
http://camflow.org/this-is-just-garbage

**Comment by michael-hahn** [comment]
If you want to see the associated code, try this link:
https://github.com/CamFlow/camflowd

Where did you get the invalid link? I personally didn't find it on the website.

**Comment by tfjmp** [comment]
https://github.com/CamFlow/website/commit/07ae89e29a86f027b419d70ef71540ca1f5fe855 fixed it.

**Comment by xyzwwwww** [comment]
The invalid link was showing up when I was clicking the "here". It's fixed now.
